### ISSUE TITLE
bug:同一目录下模型的名称可以重复

### ISSUE THREAD

**Issue by lijiajie-kiyun** [solidest/autotcg_doc#1]
![image](https://user-images.githubusercontent.com/60864251/74118670-5b5c4380-4bf7-11ea-9461-854069c55b9a.png)

**Comment by solidest** [comment]
设计初衷就是如此，原因如下：
1、模型之间不会相互引用，所以可以允许名称重复，这样会减少对用户操作的约束干扰
2、我们对标了一个知名网站 https://www.processon.com.   该网站和我们的设计一致
3、在AutoTCG专业版中，因为需要引用，所以提供了重名检查功能
