### ISSUE TITLE
首页中的测试用例数，没有及时更新。如附件图

### ISSUE THREAD

**Issue by sying2000** [solidest/autotcg_doc#11]
首页中的测试用例数，没有及时更新。如附件图
![用例数没更新](https://user-images.githubusercontent.com/50563222/74634830-a9e18300-519f-11ea-8cc6-2e2047416e78.png)

**Comment by solidest** [comment]
未能复现该问题。是否使用了浏览器的回退按钮返回我的文件？
因为浏览器回退时会自动加载上一个缓存的页面，所以数据不会刷新
使用应用本身自带的home按钮返回，数据是会正确刷新的
