### ISSUE TITLE
测试流程设计窗口没办法放大，在流程复杂的情况下，编辑流程不方便。建议在流程设计窗口和参数设置窗口间加一个关闭打开窗口功能。

### ISSUE THREAD

**Issue by sying2000** [solidest/autotcg_doc#8]
测试流程设计窗口没办法放大，在流程复杂的情况下，编辑流程不方便。建议在流程设计窗口和参数设置窗口间加一个关闭打开窗口功能。如图。
![建议加入窗口关闭按钮](https://user-images.githubusercontent.com/50563222/74393028-dc0f7f80-4e43-11ea-821d-10a0072b3628.png)

**Comment by solidest** [comment]
左下方位置添加了双箭头按钮，用来显示和隐藏设置面板
